export const BATTLE_MENU_OPTIONS = {
  FIGHT: "FIGHT",
  SWITCH: "SWITCH",
  ITEM: "ITEM",
  FLEE: "FLEE",
} as const;

export const ATTACK_MOVE_OPTIONS = {
  MOVE1: "MOVE1",
  MOVE2: "MOVE2",
  MOVE3: "MOVE3",
  MOVE4: "MOVE4",
} as const;

export const ACTIVE_BATTLE_MENU = {
  BATTLE_MAIN: "BATTLE_MAIN",
  BATTLE_MOVE_SELECT: "BATTLE_MOVE_SELECT",
  BATTLE_ITEM: "BATTLE_ITEM",
  BATTLE_SWITCH: "BATTLE_SWITCH",
  BATTLE_FLEE: "BATTLE_FLEE",
} as const;
