export const BATTLE_BACKGROUND_ASSET_KEYS = {
  FOREST: "FOREST",
} as const;

export const MONSTER_ASSET_KEYS = {
  IGUANIGNITE: "IGUANIGNITE",
  CARNODUSK: "CARNODUSK",
} as const;

export const BATTLE_ASSET_KEYS = {
  HEALTH_BAR_BACKGROUND: "HEALTH_BAR_BACKGROUND",
} as const;

export const HEALTH_BAR_ASSET_KEYS = {
  LEFT_CAP: "LEFT_CAP",
  RIGHT_CAP: "RIGHT_CAP",
  MIDDLE: "MIDDLE",
  LEFT_CAP_SHADOW: "LEFT_CAP_SHADOW",
  RIGHT_CAP_SHADOW: "RIGHT_CAP_SHADOW",
  MIDDLE_SHADOW: "MIDDLE_SHADOW",
} as const;

export const UI_ASSET_KEYS = {
  CURSOR: "CURSOR",
} as const;

export const DATA_ASSET_KEYS = {
  ATTACKS: "ATTACKS",
} as const;

export const ATTACK_ASSET_KEYS = {
  ICE_SHARD: "ICE_SHARD",
  ICE_SHARD_START: "ICE_SHARD_START",
  SLASH: "SLASH",
} as const;